# Configuration for Cloudflare Pages

[build]
command = "npm run build"

# The directory containing your static files after the build process
pages_build_output_dir = ".next"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--no-frozen-lockfile"
