# Configuration for Cloudflare Pages

[build]
command = "npm run build"

# The directory containing your static files after the build process
build_output_directory = "out"

[site]
bucket = "./out"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"
