[build]
command = "npm run build"
publish = ".next"

[build.upload]
format = "service-worker"

[site]
bucket = ".next"

[env.production]
name = "padel-page-magic-production"

[env.staging]
name = "padel-page-magic-staging"
