name = "lyautey-social-club"
main = "./.next/server/middleware-edge.js"
compatibility_date = "2023-04-20"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./.next/static"

[build.upload]
format = "directory"

# Specify the directory where your static assets are
pages_build_output_dir = ".next/standalone"
